# Generated by Django 3.2.3 on 2021-12-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_addproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buyer', models.BooleanField(default=False, verbose_name='buyer status')),
                ('is_seller', models.BooleanField(default=False, verbose_name='seller status')),
            ],
        ),
        migrations.DeleteModel(
            name='addproduct',
        ),
    ]
