# Generated by Django 3.2.3 on 2022-01-07 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_auto_20211229_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user2',
            old_name='user2',
            new_name='user1',
        ),
        migrations.AlterField(
            model_name='user1',
            name='User1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
